### PR TITLE
 X-Content-Type-Options, Subresource Integrity, CSP updates

### PR DESCRIPTION
**Pull request by rhusar**

### CODE REVIEW

**Comment by rhusar** [comment]
It's a B! https://observatory.mozilla.org/analyze/modcluster.io

**Comment by Karm** [comment]
https://github.com/eclipse/microprofile-starter/issues/184     :sob:

**Comment by rhusar** [comment]
Score: | 0/100 makes for a very easy start :)

**Comment by rhusar** [comment]
@Karm btw GH team is in the process of enabling HSTS for modcluster.io which should bring up to A or higher.

**Pull request merged**
